### PR TITLE
Reduce docker image size with mutli-stage docker build

### PR DESCRIPTION
**Pull request by shivam-sharma7**
Docker mutli-stage docker build will help to reduce docker image size.

> You can see what we have previously

Size of postgres image is 400mb
Size of Vidur codebase including node modules is 200mb
But, size of docker image: 2.4GB!!??

and, what we have now
```shell
PS C:\Users\shivam sharma\Desktop\My Project\open-source\vidur> docker image ls 
REPOSITORY   TAG           IMAGE ID       CREATED          SIZE
vidur-app    latest        f61fb1b47135   12 minutes ago   399MB
```
fixes: #100

### CODE REVIEW

**Comment by akashvarun10** [comment]
@shivam-sharma7 We already have multi-stage builds in place. However, for development purposes, we're currently limiting it to a single-stage build. Check the `Infra` Folder

**Comment by amandesai01** [comment]
I was wondering if we have any benefit keeping 2 different versions. Else, we can have primary docker file be the one with prod config.

**Comment by akashvarun10** [comment]
Separating Dockerfiles for development and production is a good practice. It also speeds up development builds since the development Dockerfile can include when you add debugging or testing tools, In production, you generally don’t mount node modules. Instead, you install them directly within the Dockerfile. 

So, I think it's better to have 2 Dockerfiles

**Comment by amandesai01** [comment]
Agreed. And now that we are awaiting for db connection, it's best to have separate files. I will close this PR then. cc: @shivam-sharma7

**Pull request closed without merging**
