### PR TITLE
Exclude some file to optimise docker build performance

### PR DESCRIPTION
**Pull request by shivam-sharma7**
fixes: #90

### CODE REVIEW

**Comment by shivam-sharma7** [comment]
review/ @akashvarun10

**Comment by shivam-sharma7** [comment]
> @shivam-sharma7 seems good, I noticed in some sample templates for Vue Nuxt that they often exclude the .nuxt folder. GPT also suggested this. I'm not entirely familiar with Vue Nuxt, should we also exclude the `.nuxt` folderand what about `docs` folder .?
Yeah, make sense
> Can you check this once again and clarify ?
We don't need both during docker image creation, so ignoring

**Review by akashvarun10 — APPROVED** [review]
@shivam-sharma7 it will be merged
@amandesai01 You can merge this PR.

**Comment by shivam-sharma7** [comment]
related https://github.com/profilecity/vidur/pull/66

**Pull request merged**
