### PR TITLE
feat: added error file

### PR DESCRIPTION
**Pull request by DEV270201**

### CODE REVIEW

**Comment by amandesai01** [comment]
@DEV270201 paste screenshot and @devshahofficial can validate.

**Comment by DEV270201** [comment]
Okay doing

**Comment by DEV270201** [comment]
image
@devshahofficial Look at this

**Comment by amandesai01** [comment]
@DEV270201 use `<Icon/>` component and choose from `icon-sets.iconify.com`

**Review by devshahofficial — APPROVED** [review]

**Comment by DEV270201** [comment]
Should I create an Icon component? its not there in the code

**Comment by amandesai01** [comment]
@DEV270201 refer other parts of codebase, see how Icons are used.

**Comment by amandesai01** [comment]
Closing due to inactivity.

**Pull request closed without merging**
