### PR TITLE
Update date formatting to display minutes, hours, days, and months

### LINKED ISSUE #146: Change Date format for Jobs posted
Date format should be updated to show minutes, later hours for the first 24 hours, then days after 24 hours, and months after 30 days.

Career site - 
Screenshot 2024-09-11 at 12 03 21 PM

Admin Dashboard - 
Screenshot 2024-09-11 at 12 04 07 PM

### PR DESCRIPTION
**Pull request by HemalDesai**
## Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [x] Bug fix (fixes an existing functionality which was not working as expected)
- [ ] Documentation change (changes to Readme.md or other docs)

## Description of Changes

This feature updates the date formatting logic to provide more granular time intervals:
- For events within the first 60 minutes: display time in minutes.
- For events between 1 and 24 hours: display time in hours.
- After 24 hours: display time in days.
- After 30 days: display time in months.

The new format ensures a more intuitive display of elapsed time for the users.

## Screenshots/Videos (if applicable)

image

## Checklist

- [ ] I have rebased the branch using `git pull origin main --rebase` and tested the feature.
- [ ] I have conducted a self-review of my code to ensure it contains only the changes related to this feature.
- [ ] I have commented my code in areas that are complex or require clarification.
- [ ] I have tested compatibility with other parts of the codebase by running the site and performing actions unrelated to my changes.

Resolves #146

### CODE REVIEW

**Review by amandesai01 — CHANGES_REQUESTED** [review]
I don't believe code works as expected. I just created a posting (~2min) and after your changes, it shows 5h ago.

**Before**
Screenshot 2024-09-12 at 8 43 35 PM

**After**
Screenshot 2024-09-12 at 8 42 51 PM

**Comment by HemalDesai** [comment]
@amandesai01  Can you please let me know the OS and browser you used ?

**Comment by amandesai01** [comment]
Macos and chrome (should not matter since this works on standard js spec thus browser/platform agnostic)

**Comment by HemalDesai** [comment]
@amandesai01 check now i guess it should work now.

**Pull request closed without merging**
