### PR TITLE
fix: ensure form labels match input IDs

### PR DESCRIPTION
**Pull request by HemalDesai**
### Description

This PR addresses the issue of mismatched form labels and input IDs across the application. The following changes have been made:

- **Verified and corrected form labels**: Ensured that every `<label>` tag has a `for` attribute that matches the corresponding `<input>` element's `id`.
- **Improved accessibility**: Corrected mismatches to enhance the accessibility of the forms for screen readers and other assistive technologies.
- **Enhanced form functionality**: Ensured proper label-input relationships to improve form usability and correctness.

### Changes

- **Updated form labels**: Corrected the `for` attribute of all `<label>` tags to match the `id` of their respective `<input>` elements.

### Related Issue

This PR fixes the issue of incorrect form labels as described in the issue https://github.com/profilecity/vidur/issues/62.

### CODE REVIEW

**Comment by amandesai01** [comment]
@HemalDesai also look at other forms, and make sure all the names are unique and as per field's intent.

**Comment by HemalDesai** [comment]
@amandesai01  I have reviewed all the forms and ensured that each input name is unique and reflects its intended purpose.

**Review by amandesai01 — CHANGES_REQUESTED** [review]
There has been miscommunication. `for` should match input's `id`

**Comment by amandesai01** [comment]
@HemalDesai you in for this? or want me to take over?

**Comment by HemalDesai** [comment]
All the input id's and label for have same values

**Pull request merged**
